id: P003028
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:35:13.903058
source_metadata:
  id: bdr:W1KG12716
  title: བཀའ་བསྲུང་དམ་ཅན་རྒྱ་མཚོའི་མཆོད་བསྟོད་དགོས་འདོད་ཀུན་འབྱུང་འཕྲིན་ལས་རབ་འབར།
  author: ''
  volumes:
    df15d8ac210840c29ff25c60ab522224:
      image_group_id: I1KG13007
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
