id: I189A4149
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:11:38+00:00'
last_modified: '2022-06-16T05:33:54.834441+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12716
  title: བཀའ་བསྲུང་དམ་ཅན་རྒྱ་མཚོའི་མཆོད་བསྟོད་དགོས་འདོད་ཀུན་འབྱུང་འཕྲིན་ལས་རབ་འབར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E16F:
      image_group_id: I1KG13007
      title: ''
      total_pages: 166
      order: 1
      base_file: E16F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
